# Generated by Django 2.1 on 2018-09-03 22:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20180902_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='subskill',
            name='category',
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, to='portfolio.Skill'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 3, 22, 17, 48, 668173, tzinfo=utc)),
        ),
    ]
