# Generated by Django 2.1 on 2018-09-04 20:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('portfolio', '0011_auto_20180904_2010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='PortfolioConfig',
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 4, 20, 31, 47, 767996, tzinfo=utc)),
        ),
    ]
