# Generated by Django 2.1 on 2018-09-04 21:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20180904_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 4, 21, 28, 35, 843376, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='featuredprojectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_images', to='portfolio.Project'),
        ),
    ]
