# Generated by Django 2.1 on 2018-09-02 06:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20180831_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='subskill',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sub_skills', to='portfolio.SkillCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subskill',
            name='skill',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sub_skills', to='portfolio.Skill'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 2, 6, 2, 56, 474769, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='skill',
            name='more_info',
            field=models.TextField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(max_length=8, unique=True),
        ),
    ]
