# Generated by Django 2.1 on 2018-09-02 06:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20180902_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 2, 6, 27, 37, 691420, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subskill',
            name='parent_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_skills', to='portfolio.Skill'),
        ),
    ]
