# Generated by Django 2.1 on 2018-09-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_auto_20180907_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, upload_to='img/projects/logos'),
        ),
        migrations.AlterField(
            model_name='featuredprojectimage',
            name='image',
            field=models.ImageField(upload_to='img/projects/images/featured'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='img/projects/images'),
        ),
    ]
