# Generated by Django 2.1 on 2018-09-05 15:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20180905_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 5, 15, 25, 56, 101656, tzinfo=utc)),
        ),
    ]
