# Generated by Django 2.1 on 2018-09-23 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_auto_20180909_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/jobs')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='logo',
            field=models.ImageField(blank=True, upload_to='img/jobs/logos'),
        ),
        migrations.AlterField(
            model_name='featuredprojectimage',
            name='image',
            field=models.ImageField(upload_to='img/projects/featured'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='img/projects'),
        ),
        migrations.AddField(
            model_name='jobimage',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.Job'),
        ),
    ]
