# Generated by Django 2.1 on 2018-09-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_auto_20180923_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='related_jobs',
            field=models.ManyToManyField(blank=True, to='portfolio.Job'),
        ),
    ]
